project:
  type: book
  output-dir: ../docs/current
  preview:
    port: 4200

book:
  title: "Open Source Software Development: A socio-technical course"
  author: "James Howison (and contributing TAs)"
  page-navigation: true
  repo-url:  https://github.com/howisonlab/open_source_software_course
  repo-subdir: quarto_course
  repo-actions: [source]
  repo-branch: master
  sidebar:
    style: "floating"
    pinned: true
  chapters:
    - index.qmd
    - oss_syllabus.qmd
    - part: "Insights"
      chapters:
      - insights/paper_plane_innovation.qmd
      - insights/what_is_open_source.qmd
      - insights/motivations.qmd
      - insights/licenses.qmd
      - insights/coordination.qmd
      - insights/governance.qmd
      - insights/examining_real_projects.qmd
      - insights/bias_lack_of_diversity.qmd
      - insights/stack_and_stream.qmd
      - insights/agile.qmd
      - insights/cybersecurity_oss.qmd
      - insights/scisoft.qmd
      
    
    - part: "Skills"
      chapters:
      - skills/paper_planes_git.qmd
      - skills/git_basic_workflow.qmd
      - skills/git_rewinding_work.qmd
      - skills/branching.qmd
      - skills/github_solo.qmd
      - skills/github_collaboration.Rmd
      - skills/git_cherrypick_split_pr.qmd
      - skills/git_rebase.qmd
    #   - skills/git_delete_history.qmd
      - skills/tests.qmd
      - skills/continuous_integration.qmd
      - skills/packaging.qmd
      
    #     - git_sharing_conflicts.qmd
    #     - git_collaboration.qmd
    #     - unit_tests.qmd
    #     - continuous_integration.qmd
    #     - git_release_management.qmd
    #     - python_packaging.qmd
    
  appendices:
    - skills/skills_faq.qmd
    - skills/glossary.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    mermaid:
      theme: default
#    highlight-style: espresso

editor: visual

