# Coordination {#sec-coordination}

Coordination is a commonly used word, meaning what needs to be done for a group to work effectively together.

In the academic field of organization science, coordination has a more specific meaning, provided by Malone and Crowston (1994)[^coordination-1].

[^coordination-1]: Malone, T. W., & Crowston, K. (1994). The interdisciplinary theory of coordination. ACM Computing Surveys, 26(1), 87--119. https://doi.org/10.1145/174666.174668 or http://ccs.mit.edu/papers/CCSWP157.html

> Coordination is managing dependencies between activities

We will learn what this means, and how it relates to motivation for participation in open source, and discuss the role that version control and repositories play.

## Pre-readings for class

-   Expectancy Theory (Wikipedia) <https://en.wikipedia.org/wiki/Expectancy_theory>

-   Expectancy Theory (useful figure): <https://web.archive.org/web/20220705161833/https://www.iedunote.com/expentancey-theory>

-   Howison, J., & Crowston, K. (2014). Collaboration through open superposition: A theory of the open source way. MIS Quarterly, 38(1), 29--50. <http://james.howison.name/pubs/howison-2014-superposition.pdf>

-   "My favorite commit": <https://dhwthompson.com/2019/my-favourite-git-commit>

## Expectancy Valance Model of Motivation

```{mermaid}
flowchart LR
    idExp[Expectancy] -->|x| idInst[Instrumentality] -->|x| idVal[Valence]
    idA[Effort] -->|x| idB[Performance] -->|x| idC[Reward]
    idQ1["Will my effort lead to high performance? Probability"] --> idQ2["Will Performance lead to outcomes?"] --> idQ3["Do I find the outcomes desirable?"]

    style idExp fill:#FFA500
    style idA fill:#FFA500
    style idQ1 fill:#FFA500

    style idInst fill:#C8A2C8
    style idB fill:#C8A2C8
    style idQ2 fill:#C8A2C8
    
    style idVal fill:#6495ED
    style idC fill:#6495ED
    style idQ3 fill:#6495ED
```

## Presentation

<iframe width="100%" height="800" src="images/Howison-PP-OpenSuperposition.pdf"></iframe>